/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 26
#define LARGE_STATE_COUNT 5
#define SYMBOL_COUNT 41
#define ALIAS_COUNT 0
#define TOKEN_COUNT 26
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 8
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 9
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_COLON = 1,
  anon_sym_let = 2,
  anon_sym_endlet = 3,
  anon_sym_add = 4,
  anon_sym_sub = 5,
  anon_sym_le = 6,
  anon_sym_eq = 7,
  anon_sym_app = 8,
  anon_sym_tapp = 9,
  anon_sym_mark = 10,
  anon_sym_grab = 11,
  anon_sym_ret = 12,
  anon_sym_halt = 13,
  anon_sym_load = 14,
  anon_sym_acc = 15,
  anon_sym_b = 16,
  anon_sym_bf = 17,
  anon_sym_clos = 18,
  aux_sym_nat_token1 = 19,
  anon_sym_0 = 20,
  aux_sym_integer_token1 = 21,
  anon_sym_true = 22,
  anon_sym_false = 23,
  sym_lab = 24,
  sym_comment = 25,
  sym_source_file = 26,
  sym_code = 27,
  sym_block = 28,
  sym_inst = 29,
  sym_cmd0 = 30,
  sym_cmd1 = 31,
  sym_load = 32,
  sym_acc = 33,
  sym_b = 34,
  sym_bf = 35,
  sym_clos = 36,
  sym_nat = 37,
  sym_integer = 38,
  sym_bool = 39,
  aux_sym_code_repeat1 = 40,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_COLON] = ":",
  [anon_sym_let] = "let",
  [anon_sym_endlet] = "endlet",
  [anon_sym_add] = "add",
  [anon_sym_sub] = "sub",
  [anon_sym_le] = "le",
  [anon_sym_eq] = "eq",
  [anon_sym_app] = "app",
  [anon_sym_tapp] = "tapp",
  [anon_sym_mark] = "mark",
  [anon_sym_grab] = "grab",
  [anon_sym_ret] = "ret",
  [anon_sym_halt] = "halt",
  [anon_sym_load] = "load",
  [anon_sym_acc] = "acc",
  [anon_sym_b] = "b",
  [anon_sym_bf] = "bf",
  [anon_sym_clos] = "clos",
  [aux_sym_nat_token1] = "nat_token1",
  [anon_sym_0] = "0",
  [aux_sym_integer_token1] = "integer_token1",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_lab] = "lab",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym_code] = "code",
  [sym_block] = "block",
  [sym_inst] = "inst",
  [sym_cmd0] = "cmd0",
  [sym_cmd1] = "cmd1",
  [sym_load] = "load",
  [sym_acc] = "acc",
  [sym_b] = "b",
  [sym_bf] = "bf",
  [sym_clos] = "clos",
  [sym_nat] = "nat",
  [sym_integer] = "integer",
  [sym_bool] = "bool",
  [aux_sym_code_repeat1] = "code_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_endlet] = anon_sym_endlet,
  [anon_sym_add] = anon_sym_add,
  [anon_sym_sub] = anon_sym_sub,
  [anon_sym_le] = anon_sym_le,
  [anon_sym_eq] = anon_sym_eq,
  [anon_sym_app] = anon_sym_app,
  [anon_sym_tapp] = anon_sym_tapp,
  [anon_sym_mark] = anon_sym_mark,
  [anon_sym_grab] = anon_sym_grab,
  [anon_sym_ret] = anon_sym_ret,
  [anon_sym_halt] = anon_sym_halt,
  [anon_sym_load] = anon_sym_load,
  [anon_sym_acc] = anon_sym_acc,
  [anon_sym_b] = anon_sym_b,
  [anon_sym_bf] = anon_sym_bf,
  [anon_sym_clos] = anon_sym_clos,
  [aux_sym_nat_token1] = aux_sym_nat_token1,
  [anon_sym_0] = anon_sym_0,
  [aux_sym_integer_token1] = aux_sym_integer_token1,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_lab] = sym_lab,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym_code] = sym_code,
  [sym_block] = sym_block,
  [sym_inst] = sym_inst,
  [sym_cmd0] = sym_cmd0,
  [sym_cmd1] = sym_cmd1,
  [sym_load] = sym_load,
  [sym_acc] = sym_acc,
  [sym_b] = sym_b,
  [sym_bf] = sym_bf,
  [sym_clos] = sym_clos,
  [sym_nat] = sym_nat,
  [sym_integer] = sym_integer,
  [sym_bool] = sym_bool,
  [aux_sym_code_repeat1] = aux_sym_code_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_endlet] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_add] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_sub] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_le] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_eq] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_app] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_tapp] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_mark] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_grab] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_ret] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_halt] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_load] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_acc] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_b] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_bf] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_clos] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_nat_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_0] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_integer_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_lab] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_code] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_inst] = {
    .visible = true,
    .named = true,
  },
  [sym_cmd0] = {
    .visible = true,
    .named = true,
  },
  [sym_cmd1] = {
    .visible = true,
    .named = true,
  },
  [sym_load] = {
    .visible = true,
    .named = true,
  },
  [sym_acc] = {
    .visible = true,
    .named = true,
  },
  [sym_b] = {
    .visible = true,
    .named = true,
  },
  [sym_bf] = {
    .visible = true,
    .named = true,
  },
  [sym_clos] = {
    .visible = true,
    .named = true,
  },
  [sym_nat] = {
    .visible = true,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_bool] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_code_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_addr = 1,
  field_cmd = 2,
  field_cmd1 = 3,
  field_code = 4,
  field_index = 5,
  field_inst = 6,
  field_lab = 7,
  field_value = 8,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_addr] = "addr",
  [field_cmd] = "cmd",
  [field_cmd1] = "cmd1",
  [field_code] = "code",
  [field_index] = "index",
  [field_inst] = "inst",
  [field_lab] = "lab",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 1},
  [5] = {.index = 4, .length = 1},
  [6] = {.index = 5, .length = 1},
  [7] = {.index = 6, .length = 1},
  [8] = {.index = 7, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_code, 0},
  [1] =
    {field_inst, 0},
  [2] =
    {field_cmd, 0},
  [3] =
    {field_cmd1, 0},
  [4] =
    {field_value, 1},
  [5] =
    {field_index, 1},
  [6] =
    {field_addr, 1},
  [7] =
    {field_inst, 2},
    {field_lab, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(43);
      ADVANCE_MAP(
        '-', 41,
        '0', 80,
        ':', 44,
        ';', 116,
        'a', 11,
        'b', 73,
        'c', 22,
        'e', 26,
        'f', 3,
        'g', 33,
        'h', 7,
        'l', 16,
        'm', 4,
        'r', 17,
        's', 39,
        't', 5,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(79);
      END_STATE();
    case 1:
      if (lookahead == '-') ADVANCE(41);
      if (lookahead == '0') ADVANCE(80);
      if (lookahead == ';') ADVANCE(116);
      if (lookahead == 'f') ADVANCE(3);
      if (lookahead == 't') ADVANCE(32);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(81);
      END_STATE();
    case 2:
      if (lookahead == ';') ADVANCE(116);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      END_STATE();
    case 3:
      if (lookahead == 'a') ADVANCE(24);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(31);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(30);
      if (lookahead == 'r') ADVANCE(40);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(10);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(23);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(14);
      END_STATE();
    case 9:
      if (lookahead == 'b') ADVANCE(51);
      END_STATE();
    case 10:
      if (lookahead == 'b') ADVANCE(63);
      END_STATE();
    case 11:
      if (lookahead == 'c') ADVANCE(12);
      if (lookahead == 'd') ADVANCE(13);
      if (lookahead == 'p') ADVANCE(28);
      END_STATE();
    case 12:
      if (lookahead == 'c') ADVANCE(71);
      END_STATE();
    case 13:
      if (lookahead == 'd') ADVANCE(49);
      END_STATE();
    case 14:
      if (lookahead == 'd') ADVANCE(69);
      END_STATE();
    case 15:
      if (lookahead == 'd') ADVANCE(25);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(53);
      if (lookahead == 'o') ADVANCE(8);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(36);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(82);
      END_STATE();
    case 19:
      if (lookahead == 'e') ADVANCE(83);
      END_STATE();
    case 20:
      if (lookahead == 'e') ADVANCE(38);
      END_STATE();
    case 21:
      if (lookahead == 'k') ADVANCE(61);
      END_STATE();
    case 22:
      if (lookahead == 'l') ADVANCE(27);
      END_STATE();
    case 23:
      if (lookahead == 'l') ADVANCE(37);
      END_STATE();
    case 24:
      if (lookahead == 'l') ADVANCE(35);
      END_STATE();
    case 25:
      if (lookahead == 'l') ADVANCE(20);
      END_STATE();
    case 26:
      if (lookahead == 'n') ADVANCE(15);
      if (lookahead == 'q') ADVANCE(55);
      END_STATE();
    case 27:
      if (lookahead == 'o') ADVANCE(34);
      END_STATE();
    case 28:
      if (lookahead == 'p') ADVANCE(57);
      END_STATE();
    case 29:
      if (lookahead == 'p') ADVANCE(59);
      END_STATE();
    case 30:
      if (lookahead == 'p') ADVANCE(29);
      END_STATE();
    case 31:
      if (lookahead == 'r') ADVANCE(21);
      END_STATE();
    case 32:
      if (lookahead == 'r') ADVANCE(40);
      END_STATE();
    case 33:
      if (lookahead == 'r') ADVANCE(6);
      END_STATE();
    case 34:
      if (lookahead == 's') ADVANCE(77);
      END_STATE();
    case 35:
      if (lookahead == 's') ADVANCE(19);
      END_STATE();
    case 36:
      if (lookahead == 't') ADVANCE(65);
      END_STATE();
    case 37:
      if (lookahead == 't') ADVANCE(67);
      END_STATE();
    case 38:
      if (lookahead == 't') ADVANCE(47);
      END_STATE();
    case 39:
      if (lookahead == 'u') ADVANCE(9);
      END_STATE();
    case 40:
      if (lookahead == 'u') ADVANCE(18);
      END_STATE();
    case 41:
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(81);
      END_STATE();
    case 42:
      if (eof) ADVANCE(43);
      ADVANCE_MAP(
        '0', 80,
        ';', 116,
        'a', 91,
        'b', 74,
        'c', 100,
        'e', 103,
        'g', 109,
        'h', 84,
        'l', 96,
        'm', 85,
        'r', 97,
        's', 114,
        't', 86,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(42);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(79);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('d' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_let);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_endlet);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_endlet);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_add);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_add);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_sub);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_sub);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_le);
      if (lookahead == 't') ADVANCE(45);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_le);
      if (lookahead == 't') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_eq);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_eq);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_app);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_app);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_tapp);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_tapp);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_mark);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_mark);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_grab);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_grab);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_ret);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_ret);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_halt);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_halt);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_load);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_load);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_acc);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_acc);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_b);
      if (lookahead == 'f') ADVANCE(75);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_b);
      if (lookahead == 'f') ADVANCE(76);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_bf);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_bf);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_clos);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_clos);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(aux_sym_nat_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(79);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_0);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(aux_sym_integer_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(81);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_lab);
      if (lookahead == 'a') ADVANCE(101);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_lab);
      if (lookahead == 'a') ADVANCE(108);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_lab);
      if (lookahead == 'a') ADVANCE(107);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_lab);
      if (lookahead == 'a') ADVANCE(90);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_lab);
      if (lookahead == 'a') ADVANCE(94);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_lab);
      if (lookahead == 'b') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_lab);
      if (lookahead == 'b') ADVANCE(64);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_lab);
      if (lookahead == 'c') ADVANCE(92);
      if (lookahead == 'd') ADVANCE(93);
      if (lookahead == 'p') ADVANCE(105);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_lab);
      if (lookahead == 'c') ADVANCE(72);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_lab);
      if (lookahead == 'd') ADVANCE(50);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_lab);
      if (lookahead == 'd') ADVANCE(70);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_lab);
      if (lookahead == 'd') ADVANCE(102);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_lab);
      if (lookahead == 'e') ADVANCE(54);
      if (lookahead == 'o') ADVANCE(88);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_lab);
      if (lookahead == 'e') ADVANCE(111);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_lab);
      if (lookahead == 'e') ADVANCE(113);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_lab);
      if (lookahead == 'k') ADVANCE(62);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_lab);
      if (lookahead == 'l') ADVANCE(104);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym_lab);
      if (lookahead == 'l') ADVANCE(112);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_lab);
      if (lookahead == 'l') ADVANCE(98);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym_lab);
      if (lookahead == 'n') ADVANCE(95);
      if (lookahead == 'q') ADVANCE(56);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym_lab);
      if (lookahead == 'o') ADVANCE(110);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_lab);
      if (lookahead == 'p') ADVANCE(58);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym_lab);
      if (lookahead == 'p') ADVANCE(60);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym_lab);
      if (lookahead == 'p') ADVANCE(106);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(sym_lab);
      if (lookahead == 'r') ADVANCE(99);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(sym_lab);
      if (lookahead == 'r') ADVANCE(87);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(sym_lab);
      if (lookahead == 's') ADVANCE(78);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(sym_lab);
      if (lookahead == 't') ADVANCE(66);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(sym_lab);
      if (lookahead == 't') ADVANCE(68);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(sym_lab);
      if (lookahead == 't') ADVANCE(48);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(sym_lab);
      if (lookahead == 'u') ADVANCE(89);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(sym_lab);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(115);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(116);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 42},
  [2] = {.lex_state = 42},
  [3] = {.lex_state = 42},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 42},
  [6] = {.lex_state = 42},
  [7] = {.lex_state = 42},
  [8] = {.lex_state = 42},
  [9] = {.lex_state = 42},
  [10] = {.lex_state = 42},
  [11] = {.lex_state = 42},
  [12] = {.lex_state = 42},
  [13] = {.lex_state = 42},
  [14] = {.lex_state = 42},
  [15] = {.lex_state = 42},
  [16] = {.lex_state = 42},
  [17] = {.lex_state = 42},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 42},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 2},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 2},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_endlet] = ACTIONS(1),
    [anon_sym_add] = ACTIONS(1),
    [anon_sym_sub] = ACTIONS(1),
    [anon_sym_le] = ACTIONS(1),
    [anon_sym_eq] = ACTIONS(1),
    [anon_sym_app] = ACTIONS(1),
    [anon_sym_tapp] = ACTIONS(1),
    [anon_sym_mark] = ACTIONS(1),
    [anon_sym_grab] = ACTIONS(1),
    [anon_sym_ret] = ACTIONS(1),
    [anon_sym_halt] = ACTIONS(1),
    [anon_sym_load] = ACTIONS(1),
    [anon_sym_acc] = ACTIONS(1),
    [anon_sym_b] = ACTIONS(1),
    [anon_sym_bf] = ACTIONS(1),
    [anon_sym_clos] = ACTIONS(1),
    [aux_sym_nat_token1] = ACTIONS(1),
    [anon_sym_0] = ACTIONS(1),
    [aux_sym_integer_token1] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(22),
    [sym_code] = STATE(23),
    [sym_block] = STATE(3),
    [sym_inst] = STATE(7),
    [sym_cmd0] = STATE(6),
    [sym_cmd1] = STATE(6),
    [sym_load] = STATE(10),
    [sym_acc] = STATE(10),
    [sym_b] = STATE(10),
    [sym_bf] = STATE(10),
    [sym_clos] = STATE(10),
    [aux_sym_code_repeat1] = STATE(3),
    [anon_sym_let] = ACTIONS(5),
    [anon_sym_endlet] = ACTIONS(5),
    [anon_sym_add] = ACTIONS(5),
    [anon_sym_sub] = ACTIONS(5),
    [anon_sym_le] = ACTIONS(5),
    [anon_sym_eq] = ACTIONS(5),
    [anon_sym_app] = ACTIONS(5),
    [anon_sym_tapp] = ACTIONS(5),
    [anon_sym_mark] = ACTIONS(5),
    [anon_sym_grab] = ACTIONS(5),
    [anon_sym_ret] = ACTIONS(5),
    [anon_sym_halt] = ACTIONS(5),
    [anon_sym_load] = ACTIONS(7),
    [anon_sym_acc] = ACTIONS(9),
    [anon_sym_b] = ACTIONS(11),
    [anon_sym_bf] = ACTIONS(13),
    [anon_sym_clos] = ACTIONS(15),
    [sym_lab] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(2)] = {
    [sym_block] = STATE(2),
    [sym_inst] = STATE(7),
    [sym_cmd0] = STATE(6),
    [sym_cmd1] = STATE(6),
    [sym_load] = STATE(10),
    [sym_acc] = STATE(10),
    [sym_b] = STATE(10),
    [sym_bf] = STATE(10),
    [sym_clos] = STATE(10),
    [aux_sym_code_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(19),
    [anon_sym_let] = ACTIONS(21),
    [anon_sym_endlet] = ACTIONS(21),
    [anon_sym_add] = ACTIONS(21),
    [anon_sym_sub] = ACTIONS(21),
    [anon_sym_le] = ACTIONS(21),
    [anon_sym_eq] = ACTIONS(21),
    [anon_sym_app] = ACTIONS(21),
    [anon_sym_tapp] = ACTIONS(21),
    [anon_sym_mark] = ACTIONS(21),
    [anon_sym_grab] = ACTIONS(21),
    [anon_sym_ret] = ACTIONS(21),
    [anon_sym_halt] = ACTIONS(21),
    [anon_sym_load] = ACTIONS(24),
    [anon_sym_acc] = ACTIONS(27),
    [anon_sym_b] = ACTIONS(30),
    [anon_sym_bf] = ACTIONS(33),
    [anon_sym_clos] = ACTIONS(36),
    [sym_lab] = ACTIONS(39),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(3)] = {
    [sym_block] = STATE(2),
    [sym_inst] = STATE(7),
    [sym_cmd0] = STATE(6),
    [sym_cmd1] = STATE(6),
    [sym_load] = STATE(10),
    [sym_acc] = STATE(10),
    [sym_b] = STATE(10),
    [sym_bf] = STATE(10),
    [sym_clos] = STATE(10),
    [aux_sym_code_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(42),
    [anon_sym_let] = ACTIONS(5),
    [anon_sym_endlet] = ACTIONS(5),
    [anon_sym_add] = ACTIONS(5),
    [anon_sym_sub] = ACTIONS(5),
    [anon_sym_le] = ACTIONS(5),
    [anon_sym_eq] = ACTIONS(5),
    [anon_sym_app] = ACTIONS(5),
    [anon_sym_tapp] = ACTIONS(5),
    [anon_sym_mark] = ACTIONS(5),
    [anon_sym_grab] = ACTIONS(5),
    [anon_sym_ret] = ACTIONS(5),
    [anon_sym_halt] = ACTIONS(5),
    [anon_sym_load] = ACTIONS(7),
    [anon_sym_acc] = ACTIONS(9),
    [anon_sym_b] = ACTIONS(11),
    [anon_sym_bf] = ACTIONS(13),
    [anon_sym_clos] = ACTIONS(15),
    [sym_lab] = ACTIONS(17),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(4)] = {
    [sym_inst] = STATE(17),
    [sym_cmd0] = STATE(6),
    [sym_cmd1] = STATE(6),
    [sym_load] = STATE(10),
    [sym_acc] = STATE(10),
    [sym_b] = STATE(10),
    [sym_bf] = STATE(10),
    [sym_clos] = STATE(10),
    [anon_sym_let] = ACTIONS(44),
    [anon_sym_endlet] = ACTIONS(44),
    [anon_sym_add] = ACTIONS(44),
    [anon_sym_sub] = ACTIONS(44),
    [anon_sym_le] = ACTIONS(5),
    [anon_sym_eq] = ACTIONS(44),
    [anon_sym_app] = ACTIONS(44),
    [anon_sym_tapp] = ACTIONS(44),
    [anon_sym_mark] = ACTIONS(44),
    [anon_sym_grab] = ACTIONS(44),
    [anon_sym_ret] = ACTIONS(44),
    [anon_sym_halt] = ACTIONS(44),
    [anon_sym_load] = ACTIONS(46),
    [anon_sym_acc] = ACTIONS(48),
    [anon_sym_b] = ACTIONS(11),
    [anon_sym_bf] = ACTIONS(50),
    [anon_sym_clos] = ACTIONS(52),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(54), 1,
      ts_builtin_sym_end,
    ACTIONS(56), 18,
      anon_sym_let,
      anon_sym_endlet,
      anon_sym_add,
      anon_sym_sub,
      anon_sym_le,
      anon_sym_eq,
      anon_sym_app,
      anon_sym_tapp,
      anon_sym_mark,
      anon_sym_grab,
      anon_sym_ret,
      anon_sym_halt,
      anon_sym_load,
      anon_sym_acc,
      anon_sym_b,
      anon_sym_bf,
      anon_sym_clos,
      sym_lab,
  [27] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(58), 1,
      ts_builtin_sym_end,
    ACTIONS(60), 18,
      anon_sym_let,
      anon_sym_endlet,
      anon_sym_add,
      anon_sym_sub,
      anon_sym_le,
      anon_sym_eq,
      anon_sym_app,
      anon_sym_tapp,
      anon_sym_mark,
      anon_sym_grab,
      anon_sym_ret,
      anon_sym_halt,
      anon_sym_load,
      anon_sym_acc,
      anon_sym_b,
      anon_sym_bf,
      anon_sym_clos,
      sym_lab,
  [54] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(62), 1,
      ts_builtin_sym_end,
    ACTIONS(64), 18,
      anon_sym_let,
      anon_sym_endlet,
      anon_sym_add,
      anon_sym_sub,
      anon_sym_le,
      anon_sym_eq,
      anon_sym_app,
      anon_sym_tapp,
      anon_sym_mark,
      anon_sym_grab,
      anon_sym_ret,
      anon_sym_halt,
      anon_sym_load,
      anon_sym_acc,
      anon_sym_b,
      anon_sym_bf,
      anon_sym_clos,
      sym_lab,
  [81] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(66), 1,
      ts_builtin_sym_end,
    ACTIONS(68), 18,
      anon_sym_let,
      anon_sym_endlet,
      anon_sym_add,
      anon_sym_sub,
      anon_sym_le,
      anon_sym_eq,
      anon_sym_app,
      anon_sym_tapp,
      anon_sym_mark,
      anon_sym_grab,
      anon_sym_ret,
      anon_sym_halt,
      anon_sym_load,
      anon_sym_acc,
      anon_sym_b,
      anon_sym_bf,
      anon_sym_clos,
      sym_lab,
  [108] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(70), 1,
      ts_builtin_sym_end,
    ACTIONS(72), 18,
      anon_sym_let,
      anon_sym_endlet,
      anon_sym_add,
      anon_sym_sub,
      anon_sym_le,
      anon_sym_eq,
      anon_sym_app,
      anon_sym_tapp,
      anon_sym_mark,
      anon_sym_grab,
      anon_sym_ret,
      anon_sym_halt,
      anon_sym_load,
      anon_sym_acc,
      anon_sym_b,
      anon_sym_bf,
      anon_sym_clos,
      sym_lab,
  [135] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(74), 1,
      ts_builtin_sym_end,
    ACTIONS(76), 18,
      anon_sym_let,
      anon_sym_endlet,
      anon_sym_add,
      anon_sym_sub,
      anon_sym_le,
      anon_sym_eq,
      anon_sym_app,
      anon_sym_tapp,
      anon_sym_mark,
      anon_sym_grab,
      anon_sym_ret,
      anon_sym_halt,
      anon_sym_load,
      anon_sym_acc,
      anon_sym_b,
      anon_sym_bf,
      anon_sym_clos,
      sym_lab,
  [162] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(78), 1,
      ts_builtin_sym_end,
    ACTIONS(80), 18,
      anon_sym_let,
      anon_sym_endlet,
      anon_sym_add,
      anon_sym_sub,
      anon_sym_le,
      anon_sym_eq,
      anon_sym_app,
      anon_sym_tapp,
      anon_sym_mark,
      anon_sym_grab,
      anon_sym_ret,
      anon_sym_halt,
      anon_sym_load,
      anon_sym_acc,
      anon_sym_b,
      anon_sym_bf,
      anon_sym_clos,
      sym_lab,
  [189] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(82), 1,
      ts_builtin_sym_end,
    ACTIONS(84), 18,
      anon_sym_let,
      anon_sym_endlet,
      anon_sym_add,
      anon_sym_sub,
      anon_sym_le,
      anon_sym_eq,
      anon_sym_app,
      anon_sym_tapp,
      anon_sym_mark,
      anon_sym_grab,
      anon_sym_ret,
      anon_sym_halt,
      anon_sym_load,
      anon_sym_acc,
      anon_sym_b,
      anon_sym_bf,
      anon_sym_clos,
      sym_lab,
  [216] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(86), 1,
      ts_builtin_sym_end,
    ACTIONS(88), 18,
      anon_sym_let,
      anon_sym_endlet,
      anon_sym_add,
      anon_sym_sub,
      anon_sym_le,
      anon_sym_eq,
      anon_sym_app,
      anon_sym_tapp,
      anon_sym_mark,
      anon_sym_grab,
      anon_sym_ret,
      anon_sym_halt,
      anon_sym_load,
      anon_sym_acc,
      anon_sym_b,
      anon_sym_bf,
      anon_sym_clos,
      sym_lab,
  [243] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(90), 1,
      ts_builtin_sym_end,
    ACTIONS(92), 18,
      anon_sym_let,
      anon_sym_endlet,
      anon_sym_add,
      anon_sym_sub,
      anon_sym_le,
      anon_sym_eq,
      anon_sym_app,
      anon_sym_tapp,
      anon_sym_mark,
      anon_sym_grab,
      anon_sym_ret,
      anon_sym_halt,
      anon_sym_load,
      anon_sym_acc,
      anon_sym_b,
      anon_sym_bf,
      anon_sym_clos,
      sym_lab,
  [270] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(94), 1,
      ts_builtin_sym_end,
    ACTIONS(96), 18,
      anon_sym_let,
      anon_sym_endlet,
      anon_sym_add,
      anon_sym_sub,
      anon_sym_le,
      anon_sym_eq,
      anon_sym_app,
      anon_sym_tapp,
      anon_sym_mark,
      anon_sym_grab,
      anon_sym_ret,
      anon_sym_halt,
      anon_sym_load,
      anon_sym_acc,
      anon_sym_b,
      anon_sym_bf,
      anon_sym_clos,
      sym_lab,
  [297] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(98), 1,
      ts_builtin_sym_end,
    ACTIONS(100), 18,
      anon_sym_let,
      anon_sym_endlet,
      anon_sym_add,
      anon_sym_sub,
      anon_sym_le,
      anon_sym_eq,
      anon_sym_app,
      anon_sym_tapp,
      anon_sym_mark,
      anon_sym_grab,
      anon_sym_ret,
      anon_sym_halt,
      anon_sym_load,
      anon_sym_acc,
      anon_sym_b,
      anon_sym_bf,
      anon_sym_clos,
      sym_lab,
  [324] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(102), 1,
      ts_builtin_sym_end,
    ACTIONS(104), 18,
      anon_sym_let,
      anon_sym_endlet,
      anon_sym_add,
      anon_sym_sub,
      anon_sym_le,
      anon_sym_eq,
      anon_sym_app,
      anon_sym_tapp,
      anon_sym_mark,
      anon_sym_grab,
      anon_sym_ret,
      anon_sym_halt,
      anon_sym_load,
      anon_sym_acc,
      anon_sym_b,
      anon_sym_bf,
      anon_sym_clos,
      sym_lab,
  [351] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(106), 2,
      anon_sym_0,
      aux_sym_integer_token1,
    ACTIONS(108), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(12), 2,
      sym_integer,
      sym_bool,
  [367] = 3,
    ACTIONS(3), 1,
      sym_comment,
    STATE(11), 1,
      sym_nat,
    ACTIONS(110), 2,
      aux_sym_nat_token1,
      anon_sym_0,
  [378] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(112), 1,
      sym_lab,
  [385] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(114), 1,
      sym_lab,
  [392] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(116), 1,
      ts_builtin_sym_end,
  [399] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(118), 1,
      ts_builtin_sym_end,
  [406] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(120), 1,
      anon_sym_COLON,
  [413] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(122), 1,
      sym_lab,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(5)] = 0,
  [SMALL_STATE(6)] = 27,
  [SMALL_STATE(7)] = 54,
  [SMALL_STATE(8)] = 81,
  [SMALL_STATE(9)] = 108,
  [SMALL_STATE(10)] = 135,
  [SMALL_STATE(11)] = 162,
  [SMALL_STATE(12)] = 189,
  [SMALL_STATE(13)] = 216,
  [SMALL_STATE(14)] = 243,
  [SMALL_STATE(15)] = 270,
  [SMALL_STATE(16)] = 297,
  [SMALL_STATE(17)] = 324,
  [SMALL_STATE(18)] = 351,
  [SMALL_STATE(19)] = 367,
  [SMALL_STATE(20)] = 378,
  [SMALL_STATE(21)] = 385,
  [SMALL_STATE(22)] = 392,
  [SMALL_STATE(23)] = 399,
  [SMALL_STATE(24)] = 406,
  [SMALL_STATE(25)] = 413,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_code_repeat1, 2, 0, 0),
  [21] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_code_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [24] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_code_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [27] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_code_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [30] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_code_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [33] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_code_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [36] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_code_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_code_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_code, 1, 0, 0),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cmd0, 1, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cmd0, 1, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inst, 1, 0, 3),
  [60] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_inst, 1, 0, 3),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 1, 0, 2),
  [64] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 1, 0, 2),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bool, 1, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bool, 1, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_integer, 1, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_integer, 1, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_cmd1, 1, 0, 4),
  [76] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_cmd1, 1, 0, 4),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_acc, 2, 0, 6),
  [80] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_acc, 2, 0, 6),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_load, 2, 0, 5),
  [84] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_load, 2, 0, 5),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_b, 2, 0, 7),
  [88] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_b, 2, 0, 7),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_clos, 2, 0, 7),
  [92] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_clos, 2, 0, 7),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bf, 2, 0, 7),
  [96] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bf, 2, 0, 7),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_nat, 1, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_nat, 1, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 8),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, 0, 8),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [116] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 1),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_avm(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "avm",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
